### ISSUE TITLE
zLink

### ISSUE THREAD

**Issue by BraveDevelopment** [Snaggly/KSW-ToolKit-Service#25]
First of all sorry for opening this issue because it is no issue.
I just didn’t know how to contact you otherwise.
I wanted to ask you about zLink. As far as I got in gathering information about this mysterious app it’s made by a Chinese company. But apart from that there is no information.
But I am really interested in this app an especially getting the source code and the technology behind it and how it works. Because I am pretty sure they didn’t get official MFI certification 😅.
But you seem to know something I think because you’re using their API or something like that?
Do you know any source that I can contact to get more information about this app and how it works. Especially getting CarPlay to work. I would be glad to hear from you. Have a nice day 🙂

**Comment by Snaggly** [comment]
Hi,
I don't know much about the inner workings of ZLINK unfortunately. They have encrypted, packed and obfuscated their application from being reverse engineered. I am only familiar with the broadcast calls it listens to, but not more. That intel I got by looking up dumpsys and reverse engineering the firmwares that ship ZLINK. 

Unfortunately I cannot help you in your research.
