### ISSUE TITLE
Feature Request:  When using advanced brightness, don't switch to dark mode during the daytime

### ISSUE THREAD

**Issue by wir3z** [Snaggly/KSW-ToolKit-Service#28]
I love the graduality with the light/dark mode + advanced brightness!

Only issue I'm seeing is if it's daytime, and the wipers come on, so do the headlights.  That triggers "dark mode" making the screen hard to see during the day.

Can we get the ability for dark mode to only be applied if advanced brightness is saying it's nighttime?

**Comment by Snaggly** [comment]
In ToolKit 2 you can choose to have timing based brightness and/or headlight based brightness. But the triggering of Dark Mode still happen when either of the two trigger. It's a good idea to make some separation that the time and headlight based triggers work independently from the Mode trigger, I'll take that into consideration for the next update 👍

![image](https://github.com/Snaggly/KSW-ToolKit-Service/assets/1353354/ca161db1-0e50-42ca-9037-3f36c38a3349)

**Comment by wir3z** [comment]
Awesome, thanks.  I do agree that some use cases may desire dark mode during the day (long tunnels, etc).
